
package GUI;

import java.io.IOException;
import java.util.Random;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Fernando
 */
public class JMemorama extends javax.swing.JFrame {
    private int[] random = new int[16];
    private boolean up=false;
    ImageIcon s1, s2;
    JButton j1, j2;
    boolean sen=false;
    int score=0;
    private Clip clip;

    /**
     * Creates new form JMemorama
     */
    public JMemorama() {
        initComponents();
        this.setLocationRelativeTo(null);
        gen();
        reproducirMusica();
        //reroll();
    }
    
    private void gen(){
        int c = 0, ca, nc;
        Random x;
        while(c<16){
            nc = 0;
            x = new Random();
            ca = x.nextInt(8)+1;
            for(int i=0; i<random.length; i++){
                if(random[i]==ca){
                    nc++;
                }
            }
            if(nc<2){
                random[c] = ca;
                c++;
            }
        }
    }
    
    private void reproducirMusica() {
        try {
            AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(getClass().getResource("Just.wav"));
            clip = AudioSystem.getClip();
            clip.open(audioInputStream);
            clip.loop(Clip.LOOP_CONTINUOUSLY);

            // Obtener el control de ganancia (volumen)
        } catch (UnsupportedAudioFileException | LineUnavailableException | IOException e) {
            e.printStackTrace();
        }
    }
    
    private void detenerMusica() {
        if (clip != null && clip.isRunning()) {
            clip.stop();
            clip.close();
        }
    }
    
    private void btnA(JButton btn){
        if(!up){
            btn.setEnabled(false);
            s1=(ImageIcon)btn.getDisabledIcon();
            j1=btn;
            up=true;
            sen=false;
        }else{
            btn.setEnabled(false);
            s2=(ImageIcon)btn.getDisabledIcon();
            j2=btn;
            sen=true;
        }
    }
    
    private void com(){
        if(up && sen){
            if(s1.getDescription().compareTo(s2.getDescription())!=0){
                j1.setEnabled(true);
                j2.setEnabled(true);
                score+=5;
            }else{
                score += 20;
                win();
            }
            up=false;
            sen=false;
        }
    }
    
    private void win(){
        if(!c1.isEnabled() && !c2.isEnabled() && !c3.isEnabled() && !c4.isEnabled() && !c5.isEnabled() && !c6.isEnabled() && !c7.isEnabled() && !c8.isEnabled() && !c9.isEnabled() && !c10.isEnabled() && !c11.isEnabled() && !c12.isEnabled() && !c13.isEnabled() && !c14.isEnabled() && !c15.isEnabled() && !c16.isEnabled()){
            JOptionPane.showMessageDialog(this, "Ganaste rey" + score, "Win", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        c1 = new javax.swing.JButton();
        c2 = new javax.swing.JButton();
        c3 = new javax.swing.JButton();
        c4 = new javax.swing.JButton();
        c5 = new javax.swing.JButton();
        c6 = new javax.swing.JButton();
        c7 = new javax.swing.JButton();
        c8 = new javax.swing.JButton();
        c9 = new javax.swing.JButton();
        c10 = new javax.swing.JButton();
        c11 = new javax.swing.JButton();
        c12 = new javax.swing.JButton();
        c13 = new javax.swing.JButton();
        c14 = new javax.swing.JButton();
        c15 = new javax.swing.JButton();
        c16 = new javax.swing.JButton();
        restart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Memorama");

        jPanel1.setLayout(new java.awt.GridLayout(4, 4));

        c1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/base.jpg"))); // NOI18N
        c1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/selec.jpg"))); // NOI18N
        c1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                c1MouseExited(evt);
            }
        });
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        jPanel1.add(c1);

        c2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/base.jpg"))); // NOI18N
        c2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/selec.jpg"))); // NOI18N
        c2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                c2MouseExited(evt);
            }
        });
        c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2ActionPerformed(evt);
            }
        });
        jPanel1.add(c2);

        c3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/base.jpg"))); // NOI18N
        c3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/selec.jpg"))); // NOI18N
        c3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                c3MouseExited(evt);
            }
        });
        c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c3ActionPerformed(evt);
            }
        });
        jPanel1.add(c3);

        c4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/base.jpg"))); // NOI18N
        c4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/selec.jpg"))); // NOI18N
        c4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                c4MouseExited(evt);
            }
        });
        c4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c4ActionPerformed(evt);
            }
        });
        jPanel1.add(c4);

        c5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/base.jpg"))); // NOI18N
        c5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/selec.jpg"))); // NOI18N
        c5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                c5MouseExited(evt);
            }
        });
        c5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c5ActionPerformed(evt);
            }
        });
        jPanel1.add(c5);

        c6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/base.jpg"))); // NOI18N
        c6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/selec.jpg"))); // NOI18N
        c6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                c6MouseExited(evt);
            }
        });
        c6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c6ActionPerformed(evt);
            }
        });
        jPanel1.add(c6);

        c7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/base.jpg"))); // NOI18N
        c7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/selec.jpg"))); // NOI18N
        c7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                c7MouseExited(evt);
            }
        });
        c7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c7ActionPerformed(evt);
            }
        });
        jPanel1.add(c7);

        c8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/base.jpg"))); // NOI18N
        c8.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/selec.jpg"))); // NOI18N
        c8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                c8MouseExited(evt);
            }
        });
        c8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c8ActionPerformed(evt);
            }
        });
        jPanel1.add(c8);

        c9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/base.jpg"))); // NOI18N
        c9.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/selec.jpg"))); // NOI18N
        c9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                c9MouseExited(evt);
            }
        });
        c9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c9ActionPerformed(evt);
            }
        });
        jPanel1.add(c9);

        c10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/base.jpg"))); // NOI18N
        c10.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/selec.jpg"))); // NOI18N
        c10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                c10MouseExited(evt);
            }
        });
        c10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c10ActionPerformed(evt);
            }
        });
        jPanel1.add(c10);

        c11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/base.jpg"))); // NOI18N
        c11.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/selec.jpg"))); // NOI18N
        c11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                c11MouseExited(evt);
            }
        });
        c11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c11ActionPerformed(evt);
            }
        });
        jPanel1.add(c11);

        c12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/base.jpg"))); // NOI18N
        c12.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/selec.jpg"))); // NOI18N
        c12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                c12MouseExited(evt);
            }
        });
        c12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c12ActionPerformed(evt);
            }
        });
        jPanel1.add(c12);

        c13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/base.jpg"))); // NOI18N
        c13.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/selec.jpg"))); // NOI18N
        c13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                c13MouseExited(evt);
            }
        });
        c13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c13ActionPerformed(evt);
            }
        });
        jPanel1.add(c13);

        c14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/base.jpg"))); // NOI18N
        c14.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/selec.jpg"))); // NOI18N
        c14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                c14MouseExited(evt);
            }
        });
        c14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c14ActionPerformed(evt);
            }
        });
        jPanel1.add(c14);

        c15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/base.jpg"))); // NOI18N
        c15.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/selec.jpg"))); // NOI18N
        c15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                c15MouseExited(evt);
            }
        });
        c15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c15ActionPerformed(evt);
            }
        });
        jPanel1.add(c15);

        c16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/base.jpg"))); // NOI18N
        c16.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/selec.jpg"))); // NOI18N
        c16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                c16MouseExited(evt);
            }
        });
        c16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c16ActionPerformed(evt);
            }
        });
        jPanel1.add(c16);

        restart.setText("Reiniciar");
        restart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(restart, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(restart, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void c16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c16ActionPerformed
        // TODO add your handling code here:
        c16.setDisabledIcon(new  ImageIcon(getClass().getResource("../images/ca"+random[15]+".jpg")));
        btnA(c16);
    }//GEN-LAST:event_c16ActionPerformed

    private void restartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restartActionPerformed
        // TODO add your handling code here:
        c1.setEnabled(true);
        c2.setEnabled(true);
        c3.setEnabled(true);
        c4.setEnabled(true);
        
        c5.setEnabled(true);
        c6.setEnabled(true);
        c7.setEnabled(true);
        c8.setEnabled(true);
        
        c9.setEnabled(true);
        c10.setEnabled(true);
        c11.setEnabled(true);
        c12.setEnabled(true);
        
        c13.setEnabled(true);
        c14.setEnabled(true);
        c15.setEnabled(true);
        c16.setEnabled(true);
        
        up=false;
        sen=false;
        score=0;
    }//GEN-LAST:event_restartActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        // TODO add your handling code here:
        c1.setDisabledIcon(new  ImageIcon(getClass().getResource("../images/ca"+random[0]+".jpg")));
        btnA(c1);
    }//GEN-LAST:event_c1ActionPerformed

    private void c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2ActionPerformed
        // TODO add your handling code here:
        c2.setDisabledIcon(new  ImageIcon(getClass().getResource("../images/ca"+random[1]+".jpg")));
        btnA(c2);
    }//GEN-LAST:event_c2ActionPerformed

    private void c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c3ActionPerformed
        // TODO add your handling code here:
        c3.setDisabledIcon(new  ImageIcon(getClass().getResource("../images/ca"+random[2]+".jpg")));
        btnA(c3);
    }//GEN-LAST:event_c3ActionPerformed

    private void c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c4ActionPerformed
        // TODO add your handling code here:
        c4.setDisabledIcon(new  ImageIcon(getClass().getResource("../images/ca"+random[3]+".jpg")));
        btnA(c4);
    }//GEN-LAST:event_c4ActionPerformed

    private void c5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c5ActionPerformed
        // TODO add your handling code here:
        c5.setDisabledIcon(new  ImageIcon(getClass().getResource("../images/ca"+random[4]+".jpg")));
        btnA(c5);
    }//GEN-LAST:event_c5ActionPerformed

    private void c6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c6ActionPerformed
        // TODO add your handling code here:
        c6.setDisabledIcon(new  ImageIcon(getClass().getResource("../images/ca"+random[5]+".jpg")));
        btnA(c6);
    }//GEN-LAST:event_c6ActionPerformed

    private void c7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c7ActionPerformed
        // TODO add your handling code here:
        c7.setDisabledIcon(new  ImageIcon(getClass().getResource("../images/ca"+random[6]+".jpg")));
        btnA(c7);
    }//GEN-LAST:event_c7ActionPerformed

    private void c8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c8ActionPerformed
        // TODO add your handling code here:
        c8.setDisabledIcon(new  ImageIcon(getClass().getResource("../images/ca"+random[7]+".jpg")));
        btnA(c8);
    }//GEN-LAST:event_c8ActionPerformed

    private void c9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c9ActionPerformed
        // TODO add your handling code here:
        c9.setDisabledIcon(new  ImageIcon(getClass().getResource("../images/ca"+random[8]+".jpg")));
        btnA(c9);
    }//GEN-LAST:event_c9ActionPerformed

    private void c10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c10ActionPerformed
        // TODO add your handling code here:
        c10.setDisabledIcon(new  ImageIcon(getClass().getResource("../images/ca"+random[9]+".jpg")));
        btnA(c10);
    }//GEN-LAST:event_c10ActionPerformed

    private void c11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c11ActionPerformed
        // TODO add your handling code here:
        c11.setDisabledIcon(new  ImageIcon(getClass().getResource("../images/ca"+random[10]+".jpg")));
        btnA(c11);
    }//GEN-LAST:event_c11ActionPerformed

    private void c12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c12ActionPerformed
        // TODO add your handling code here:
        c12.setDisabledIcon(new  ImageIcon(getClass().getResource("../images/ca"+random[11]+".jpg")));
        btnA(c12);
    }//GEN-LAST:event_c12ActionPerformed

    private void c13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c13ActionPerformed
        // TODO add your handling code here:
        c13.setDisabledIcon(new  ImageIcon(getClass().getResource("../images/ca"+random[12]+".jpg")));
        btnA(c13);
    }//GEN-LAST:event_c13ActionPerformed

    private void c14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c14ActionPerformed
        // TODO add your handling code here:
        c14.setDisabledIcon(new  ImageIcon(getClass().getResource("../images/ca"+random[13]+".jpg")));
        btnA(c14);
    }//GEN-LAST:event_c14ActionPerformed

    private void c15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c15ActionPerformed
        // TODO add your handling code here:
        c15.setDisabledIcon(new  ImageIcon(getClass().getResource("../images/ca"+random[14]+".jpg")));
        btnA(c15);
    }//GEN-LAST:event_c15ActionPerformed

    private void c1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c1MouseExited
        // TODO add your handling code here:
        
        com();
    }//GEN-LAST:event_c1MouseExited

    private void c2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c2MouseExited
        // TODO add your handling code here:
        
        com();
    }//GEN-LAST:event_c2MouseExited

    private void c3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c3MouseExited
        // TODO add your handling code here:
        
        com();
    }//GEN-LAST:event_c3MouseExited

    private void c4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c4MouseExited
        // TODO add your handling code here:
        
        com();
    }//GEN-LAST:event_c4MouseExited

    private void c5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c5MouseExited
        // TODO add your handling code here:
        
        com();
    }//GEN-LAST:event_c5MouseExited

    private void c6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c6MouseExited
        // TODO add your handling code here:
        
        com();
    }//GEN-LAST:event_c6MouseExited

    private void c7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c7MouseExited
        // TODO add your handling code here:
        
        com();
    }//GEN-LAST:event_c7MouseExited

    private void c8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c8MouseExited
        // TODO add your handling code here:
        
        com();
    }//GEN-LAST:event_c8MouseExited

    private void c9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c9MouseExited
        // TODO add your handling code here:
        
        com();
    }//GEN-LAST:event_c9MouseExited

    private void c10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c10MouseExited
        // TODO add your handling code here:
        
        com();
    }//GEN-LAST:event_c10MouseExited

    private void c11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c11MouseExited
        // TODO add your handling code here:
        
        com();
    }//GEN-LAST:event_c11MouseExited

    private void c12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c12MouseExited
        // TODO add your handling code here:
        
        com();
    }//GEN-LAST:event_c12MouseExited

    private void c13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c13MouseExited
        // TODO add your handling code here:
        
        com();
    }//GEN-LAST:event_c13MouseExited

    private void c14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c14MouseExited
        // TODO add your handling code here:
        
        com();
    }//GEN-LAST:event_c14MouseExited

    private void c15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c15MouseExited
        // TODO add your handling code here:
        
        com();
    }//GEN-LAST:event_c15MouseExited

    private void c16MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c16MouseExited
        // TODO add your handling code here:
       
        com();
    }//GEN-LAST:event_c16MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JMemorama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JMemorama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JMemorama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JMemorama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JMemorama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton c1;
    private javax.swing.JButton c10;
    private javax.swing.JButton c11;
    private javax.swing.JButton c12;
    private javax.swing.JButton c13;
    private javax.swing.JButton c14;
    private javax.swing.JButton c15;
    private javax.swing.JButton c16;
    private javax.swing.JButton c2;
    private javax.swing.JButton c3;
    private javax.swing.JButton c4;
    private javax.swing.JButton c5;
    private javax.swing.JButton c6;
    private javax.swing.JButton c7;
    private javax.swing.JButton c8;
    private javax.swing.JButton c9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton restart;
    // End of variables declaration//GEN-END:variables
}
